apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KCSJhdXRocyI6IHsNCgkJImdoY3IuaW8iOiB7DQoJCQkiYXV0aCI6ICJZblZuZFhKemFHbHJPbWRvY0Y5SmJ6TlRSbWw2YlRCbFlsRkNja3RQTmpGUk5FZHJRV0YxVUhaaWNHMHdiRmQ1Y2tFPSINCgkJfQ0KCX0sDQoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsDQoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiDQp9
type: kubernetes.io/dockerconfigjson
